name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.9

      - name: Use Node.js 16.15.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
          cache: 'pnpm'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13

      - name: Copy readme to backend
        run: cp README.md backend/

      - name: Install JS dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build chainlit
        run: |
          pnpm run build
          poetry build --format wheel
        working-directory: ./backend

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./backend/dist/*.whl
          asset_name: chainlit-${{ github.ref }}.whl
          asset_content_type: application/zip